// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/abronan/todo-grpc/api/todo/v1/todo.proto

/*
Package todo is a generated protocol buffer package.

It is generated from these files:
	github.com/abronan/todo-grpc/api/todo/v1/todo.proto

It has these top-level messages:
	Todo
	CreateTodoRequest
	CreateTodoResponse
	CreateTodosRequest
	CreateTodosResponse
	GetTodoRequest
	GetTodoResponse
	ListTodoRequest
	ListTodoResponse
	DeleteTodoRequest
	DeleteTodoResponse
	UpdateTodoRequest
	UpdateTodoResponse
	UpdateTodosRequest
	UpdateTodosResponse
*/
package todo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/gogo/protobuf/types"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Todo struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	// @inject_tag: sql:",notnull,default:false"
	Completed bool `protobuf:"varint,4,opt,name=completed" json:"completed,omitempty" sql:",notnull,default:false"`
	// @inject_tag: sql:"type:timestamptz,default:now()"
	CreatedAt *google_protobuf1.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt" json:"created_at,omitempty" sql:"type:timestamptz,default:now()"`
	// @inject_tag: sql:"type:timestamptz"
	UpdatedAt *google_protobuf1.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty" sql:"type:timestamptz"`
}

func (m *Todo) Reset()                    { *m = Todo{} }
func (m *Todo) String() string            { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()               {}
func (*Todo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Todo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Todo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Todo) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *Todo) GetCreatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Todo) GetUpdatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type CreateTodoRequest struct {
	Item *Todo `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
}

func (m *CreateTodoRequest) Reset()                    { *m = CreateTodoRequest{} }
func (m *CreateTodoRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateTodoRequest) ProtoMessage()               {}
func (*CreateTodoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateTodoRequest) GetItem() *Todo {
	if m != nil {
		return m.Item
	}
	return nil
}

type CreateTodoResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateTodoResponse) Reset()                    { *m = CreateTodoResponse{} }
func (m *CreateTodoResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateTodoResponse) ProtoMessage()               {}
func (*CreateTodoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateTodoResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateTodosRequest struct {
	Items []*Todo `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *CreateTodosRequest) Reset()                    { *m = CreateTodosRequest{} }
func (m *CreateTodosRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateTodosRequest) ProtoMessage()               {}
func (*CreateTodosRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateTodosRequest) GetItems() []*Todo {
	if m != nil {
		return m.Items
	}
	return nil
}

type CreateTodosResponse struct {
	Ids []string `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
}

func (m *CreateTodosResponse) Reset()                    { *m = CreateTodosResponse{} }
func (m *CreateTodosResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateTodosResponse) ProtoMessage()               {}
func (*CreateTodosResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateTodosResponse) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetTodoRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetTodoRequest) Reset()                    { *m = GetTodoRequest{} }
func (m *GetTodoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTodoRequest) ProtoMessage()               {}
func (*GetTodoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetTodoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetTodoResponse struct {
	Item *Todo `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
}

func (m *GetTodoResponse) Reset()                    { *m = GetTodoResponse{} }
func (m *GetTodoResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTodoResponse) ProtoMessage()               {}
func (*GetTodoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetTodoResponse) GetItem() *Todo {
	if m != nil {
		return m.Item
	}
	return nil
}

type ListTodoRequest struct {
	Limit        int32 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	NotCompleted bool  `protobuf:"varint,2,opt,name=not_completed,json=notCompleted" json:"not_completed,omitempty"`
}

func (m *ListTodoRequest) Reset()                    { *m = ListTodoRequest{} }
func (m *ListTodoRequest) String() string            { return proto.CompactTextString(m) }
func (*ListTodoRequest) ProtoMessage()               {}
func (*ListTodoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ListTodoRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListTodoRequest) GetNotCompleted() bool {
	if m != nil {
		return m.NotCompleted
	}
	return false
}

type ListTodoResponse struct {
	Items []*Todo `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *ListTodoResponse) Reset()                    { *m = ListTodoResponse{} }
func (m *ListTodoResponse) String() string            { return proto.CompactTextString(m) }
func (*ListTodoResponse) ProtoMessage()               {}
func (*ListTodoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ListTodoResponse) GetItems() []*Todo {
	if m != nil {
		return m.Items
	}
	return nil
}

type DeleteTodoRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteTodoRequest) Reset()                    { *m = DeleteTodoRequest{} }
func (m *DeleteTodoRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteTodoRequest) ProtoMessage()               {}
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeleteTodoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteTodoResponse struct {
}

func (m *DeleteTodoResponse) Reset()                    { *m = DeleteTodoResponse{} }
func (m *DeleteTodoResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteTodoResponse) ProtoMessage()               {}
func (*DeleteTodoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type UpdateTodoRequest struct {
	Item *Todo `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
}

func (m *UpdateTodoRequest) Reset()                    { *m = UpdateTodoRequest{} }
func (m *UpdateTodoRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateTodoRequest) ProtoMessage()               {}
func (*UpdateTodoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *UpdateTodoRequest) GetItem() *Todo {
	if m != nil {
		return m.Item
	}
	return nil
}

type UpdateTodoResponse struct {
}

func (m *UpdateTodoResponse) Reset()                    { *m = UpdateTodoResponse{} }
func (m *UpdateTodoResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateTodoResponse) ProtoMessage()               {}
func (*UpdateTodoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type UpdateTodosRequest struct {
	Items []*Todo `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *UpdateTodosRequest) Reset()                    { *m = UpdateTodosRequest{} }
func (m *UpdateTodosRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateTodosRequest) ProtoMessage()               {}
func (*UpdateTodosRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *UpdateTodosRequest) GetItems() []*Todo {
	if m != nil {
		return m.Items
	}
	return nil
}

type UpdateTodosResponse struct {
}

func (m *UpdateTodosResponse) Reset()                    { *m = UpdateTodosResponse{} }
func (m *UpdateTodosResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateTodosResponse) ProtoMessage()               {}
func (*UpdateTodosResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func init() {
	proto.RegisterType((*Todo)(nil), "todo.v1.Todo")
	proto.RegisterType((*CreateTodoRequest)(nil), "todo.v1.CreateTodoRequest")
	proto.RegisterType((*CreateTodoResponse)(nil), "todo.v1.CreateTodoResponse")
	proto.RegisterType((*CreateTodosRequest)(nil), "todo.v1.CreateTodosRequest")
	proto.RegisterType((*CreateTodosResponse)(nil), "todo.v1.CreateTodosResponse")
	proto.RegisterType((*GetTodoRequest)(nil), "todo.v1.GetTodoRequest")
	proto.RegisterType((*GetTodoResponse)(nil), "todo.v1.GetTodoResponse")
	proto.RegisterType((*ListTodoRequest)(nil), "todo.v1.ListTodoRequest")
	proto.RegisterType((*ListTodoResponse)(nil), "todo.v1.ListTodoResponse")
	proto.RegisterType((*DeleteTodoRequest)(nil), "todo.v1.DeleteTodoRequest")
	proto.RegisterType((*DeleteTodoResponse)(nil), "todo.v1.DeleteTodoResponse")
	proto.RegisterType((*UpdateTodoRequest)(nil), "todo.v1.UpdateTodoRequest")
	proto.RegisterType((*UpdateTodoResponse)(nil), "todo.v1.UpdateTodoResponse")
	proto.RegisterType((*UpdateTodosRequest)(nil), "todo.v1.UpdateTodosRequest")
	proto.RegisterType((*UpdateTodosResponse)(nil), "todo.v1.UpdateTodosResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TodoService service

type TodoServiceClient interface {
	CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*CreateTodoResponse, error)
	// Bulk version of CreateTodo
	CreateTodos(ctx context.Context, in *CreateTodosRequest, opts ...grpc.CallOption) (*CreateTodosResponse, error)
	GetTodo(ctx context.Context, in *GetTodoRequest, opts ...grpc.CallOption) (*GetTodoResponse, error)
	ListTodo(ctx context.Context, in *ListTodoRequest, opts ...grpc.CallOption) (*ListTodoResponse, error)
	DeleteTodo(ctx context.Context, in *DeleteTodoRequest, opts ...grpc.CallOption) (*DeleteTodoResponse, error)
	UpdateTodo(ctx context.Context, in *UpdateTodoRequest, opts ...grpc.CallOption) (*UpdateTodoResponse, error)
	UpdateTodos(ctx context.Context, in *UpdateTodosRequest, opts ...grpc.CallOption) (*UpdateTodosResponse, error)
}

type todoServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoServiceClient(cc *grpc.ClientConn) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*CreateTodoResponse, error) {
	out := new(CreateTodoResponse)
	err := grpc.Invoke(ctx, "/todo.v1.TodoService/CreateTodo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) CreateTodos(ctx context.Context, in *CreateTodosRequest, opts ...grpc.CallOption) (*CreateTodosResponse, error) {
	out := new(CreateTodosResponse)
	err := grpc.Invoke(ctx, "/todo.v1.TodoService/CreateTodos", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) GetTodo(ctx context.Context, in *GetTodoRequest, opts ...grpc.CallOption) (*GetTodoResponse, error) {
	out := new(GetTodoResponse)
	err := grpc.Invoke(ctx, "/todo.v1.TodoService/GetTodo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) ListTodo(ctx context.Context, in *ListTodoRequest, opts ...grpc.CallOption) (*ListTodoResponse, error) {
	out := new(ListTodoResponse)
	err := grpc.Invoke(ctx, "/todo.v1.TodoService/ListTodo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) DeleteTodo(ctx context.Context, in *DeleteTodoRequest, opts ...grpc.CallOption) (*DeleteTodoResponse, error) {
	out := new(DeleteTodoResponse)
	err := grpc.Invoke(ctx, "/todo.v1.TodoService/DeleteTodo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) UpdateTodo(ctx context.Context, in *UpdateTodoRequest, opts ...grpc.CallOption) (*UpdateTodoResponse, error) {
	out := new(UpdateTodoResponse)
	err := grpc.Invoke(ctx, "/todo.v1.TodoService/UpdateTodo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) UpdateTodos(ctx context.Context, in *UpdateTodosRequest, opts ...grpc.CallOption) (*UpdateTodosResponse, error) {
	out := new(UpdateTodosResponse)
	err := grpc.Invoke(ctx, "/todo.v1.TodoService/UpdateTodos", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TodoService service

type TodoServiceServer interface {
	CreateTodo(context.Context, *CreateTodoRequest) (*CreateTodoResponse, error)
	// Bulk version of CreateTodo
	CreateTodos(context.Context, *CreateTodosRequest) (*CreateTodosResponse, error)
	GetTodo(context.Context, *GetTodoRequest) (*GetTodoResponse, error)
	ListTodo(context.Context, *ListTodoRequest) (*ListTodoResponse, error)
	DeleteTodo(context.Context, *DeleteTodoRequest) (*DeleteTodoResponse, error)
	UpdateTodo(context.Context, *UpdateTodoRequest) (*UpdateTodoResponse, error)
	UpdateTodos(context.Context, *UpdateTodosRequest) (*UpdateTodosResponse, error)
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_CreateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).CreateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.v1.TodoService/CreateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).CreateTodo(ctx, req.(*CreateTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_CreateTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTodosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).CreateTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.v1.TodoService/CreateTodos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).CreateTodos(ctx, req.(*CreateTodosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_GetTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).GetTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.v1.TodoService/GetTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).GetTodo(ctx, req.(*GetTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_ListTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).ListTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.v1.TodoService/ListTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).ListTodo(ctx, req.(*ListTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_DeleteTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).DeleteTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.v1.TodoService/DeleteTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).DeleteTodo(ctx, req.(*DeleteTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_UpdateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).UpdateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.v1.TodoService/UpdateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).UpdateTodo(ctx, req.(*UpdateTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_UpdateTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTodosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).UpdateTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.v1.TodoService/UpdateTodos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).UpdateTodos(ctx, req.(*UpdateTodosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todo.v1.TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTodo",
			Handler:    _TodoService_CreateTodo_Handler,
		},
		{
			MethodName: "CreateTodos",
			Handler:    _TodoService_CreateTodos_Handler,
		},
		{
			MethodName: "GetTodo",
			Handler:    _TodoService_GetTodo_Handler,
		},
		{
			MethodName: "ListTodo",
			Handler:    _TodoService_ListTodo_Handler,
		},
		{
			MethodName: "DeleteTodo",
			Handler:    _TodoService_DeleteTodo_Handler,
		},
		{
			MethodName: "UpdateTodo",
			Handler:    _TodoService_UpdateTodo_Handler,
		},
		{
			MethodName: "UpdateTodos",
			Handler:    _TodoService_UpdateTodos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/abronan/todo-grpc/api/todo/v1/todo.proto",
}

func init() {
	proto.RegisterFile("github.com/abronan/todo-grpc/api/todo/v1/todo.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 629 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xc7, 0xe5, 0x34, 0x6e, 0x9b, 0xc9, 0xaf, 0x6d, 0x3a, 0x4d, 0x7f, 0x18, 0x53, 0x09, 0xe3,
	0x22, 0x51, 0x55, 0xc2, 0x56, 0x5b, 0x04, 0x4a, 0x6f, 0xa5, 0x48, 0x5c, 0x7a, 0xc1, 0x2d, 0x17,
	0x44, 0x55, 0xf9, 0xcf, 0x12, 0x56, 0xc4, 0x5e, 0x63, 0x6f, 0x72, 0x41, 0x5c, 0x78, 0x05, 0x4e,
	0x3c, 0x17, 0x6f, 0x80, 0x78, 0x10, 0xe4, 0xf5, 0x3a, 0xde, 0xc4, 0x16, 0xb4, 0xa7, 0x64, 0x77,
	0x66, 0x3e, 0x3b, 0x33, 0xdf, 0xaf, 0x0c, 0x27, 0x63, 0xca, 0x3f, 0x4e, 0x03, 0x27, 0x64, 0xb1,
	0xeb, 0x07, 0x19, 0x4b, 0xfc, 0xc4, 0xe5, 0x2c, 0x62, 0x4f, 0xc7, 0x59, 0x1a, 0xba, 0x7e, 0x4a,
	0xc5, 0xc9, 0x9d, 0x1d, 0x89, 0x5f, 0x27, 0xcd, 0x18, 0x67, 0xb8, 0x26, 0xfe, 0xcf, 0x8e, 0xcc,
	0xbd, 0x31, 0x63, 0xe3, 0x09, 0x11, 0x79, 0x7e, 0x92, 0x30, 0xee, 0x73, 0xca, 0x92, 0xbc, 0x4c,
	0x33, 0x1f, 0xca, 0xa8, 0x38, 0x05, 0xd3, 0x0f, 0x2e, 0xa7, 0x31, 0xc9, 0xb9, 0x1f, 0xa7, 0x65,
	0x82, 0xfd, 0x4b, 0x83, 0xee, 0x15, 0x8b, 0x18, 0x6e, 0x42, 0x87, 0x46, 0x86, 0x66, 0x69, 0x07,
	0x3d, 0xaf, 0x43, 0x23, 0x1c, 0x82, 0xce, 0x29, 0x9f, 0x10, 0xa3, 0x23, 0xae, 0xca, 0x03, 0x5a,
	0xd0, 0x8f, 0x48, 0x1e, 0x66, 0x34, 0x2d, 0x5e, 0x31, 0x56, 0x44, 0x4c, 0xbd, 0xc2, 0x3d, 0xe8,
	0x85, 0x2c, 0x4e, 0x27, 0x84, 0x93, 0xc8, 0xe8, 0x5a, 0xda, 0xc1, 0xba, 0x57, 0x5f, 0xe0, 0x08,
	0x20, 0xcc, 0x88, 0xcf, 0x49, 0x74, 0xe3, 0x73, 0x43, 0xb7, 0xb4, 0x83, 0xfe, 0xb1, 0xe9, 0x94,
	0x4d, 0x3a, 0x55, 0x93, 0xce, 0x55, 0xd5, 0xa4, 0xd7, 0x93, 0xd9, 0x67, 0xbc, 0x28, 0x9d, 0xa6,
	0x51, 0x55, 0xba, 0xfa, 0xef, 0x52, 0x99, 0x7d, 0xc6, 0xed, 0xe7, 0xb0, 0x7d, 0x2e, 0x38, 0xc5,
	0xa4, 0x1e, 0xf9, 0x3c, 0x25, 0x39, 0xc7, 0x47, 0xd0, 0xa5, 0x9c, 0xc4, 0x62, 0xe4, 0xfe, 0xf1,
	0x86, 0x23, 0x17, 0xea, 0x88, 0x1c, 0x11, 0xb2, 0x1f, 0x03, 0xaa, 0x75, 0x79, 0xca, 0x92, 0x9c,
	0x2c, 0x6f, 0xca, 0x1e, 0xa9, 0x59, 0x79, 0x85, 0xdf, 0x07, 0xbd, 0x60, 0xe4, 0x86, 0x66, 0xad,
	0x34, 0xf9, 0x65, 0xcc, 0x7e, 0x02, 0x3b, 0x0b, 0xa5, 0xf2, 0x85, 0x01, 0xac, 0xd0, 0xa8, 0xac,
	0xec, 0x79, 0xc5, 0x5f, 0xdb, 0x82, 0xcd, 0xd7, 0x84, 0xab, 0xed, 0x2f, 0x77, 0xf1, 0x0c, 0xb6,
	0xe6, 0x19, 0x12, 0x73, 0x8b, 0x09, 0x2f, 0x60, 0xeb, 0x82, 0xe6, 0x0b, 0xe0, 0x21, 0xe8, 0x13,
	0x1a, 0x53, 0x2e, 0xca, 0x74, 0xaf, 0x3c, 0xe0, 0x3e, 0x6c, 0x24, 0x8c, 0xdf, 0xd4, 0xd2, 0x76,
	0x84, 0xb4, 0xff, 0x25, 0x8c, 0x9f, 0x57, 0x77, 0xf6, 0x0b, 0x18, 0xd4, 0x34, 0xd9, 0xc4, 0xad,
	0xf6, 0xb0, 0x0f, 0xdb, 0xaf, 0x48, 0xc1, 0xf8, 0xdb, 0x84, 0x43, 0x40, 0x35, 0xa9, 0xe4, 0x17,
	0xda, 0xbe, 0x15, 0x42, 0xdf, 0x51, 0xdb, 0x21, 0xa0, 0x5a, 0x27, 0x69, 0x23, 0xf5, 0xf6, 0x6e,
	0x5a, 0xee, 0xc2, 0xce, 0x42, 0x69, 0x49, 0x3c, 0xfe, 0xa1, 0x43, 0xbf, 0xb8, 0xb9, 0x24, 0xd9,
	0x8c, 0x86, 0x04, 0xaf, 0x01, 0x6a, 0xc9, 0xd1, 0x9c, 0xa3, 0x1a, 0x06, 0x35, 0x1f, 0xb4, 0xc6,
	0x64, 0xa3, 0xff, 0x7f, 0xfb, 0xf9, 0xfb, 0x7b, 0x67, 0x60, 0xaf, 0x57, 0xdf, 0x85, 0x53, 0x31,
	0x16, 0x06, 0xd0, 0x57, 0x1c, 0x85, 0x6d, 0x8c, 0x6a, 0x2c, 0x73, 0xaf, 0x3d, 0x28, 0x5f, 0x30,
	0xc4, 0x0b, 0x68, 0x6f, 0x54, 0x2f, 0xb8, 0xc1, 0x74, 0xf2, 0xe9, 0x54, 0x3b, 0xc4, 0x4b, 0x58,
	0x93, 0x56, 0xc3, 0x7b, 0x73, 0xc4, 0xa2, 0x3d, 0x4d, 0xa3, 0x19, 0x90, 0xdc, 0x5d, 0xc1, 0xdd,
	0xc2, 0x9a, 0xfb, 0x85, 0x46, 0x5f, 0xf1, 0x0d, 0xac, 0x57, 0xde, 0xc1, 0xba, 0x78, 0xc9, 0x9c,
	0xe6, 0xfd, 0x96, 0x88, 0xe4, 0x0e, 0x04, 0x17, 0x70, 0xbe, 0x11, 0x7c, 0x0f, 0x50, 0x1b, 0x46,
	0x59, 0x75, 0xc3, 0x6a, 0xca, 0xaa, 0x5b, 0x1c, 0x26, 0x1b, 0x3e, 0x5c, 0x6a, 0xf8, 0x1a, 0xa0,
	0xd6, 0x5b, 0xa1, 0x37, 0xdc, 0xa8, 0xd0, 0x5b, 0x1c, 0x27, 0x85, 0x34, 0x5b, 0x84, 0x54, 0xec,
	0x84, 0x6d, 0x8c, 0x16, 0x21, 0x5b, 0x1c, 0x58, 0x09, 0x69, 0x36, 0x84, 0x7c, 0xb9, 0xfa, 0xae,
	0x5b, 0x9c, 0x83, 0x55, 0xf1, 0xf9, 0x3c, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xa8, 0x8f,
	0xbc, 0x8a, 0x06, 0x00, 0x00,
}
